Add endpoints related to pages in the service configuration
Financial-Times/publish-availability-monitor pull request #190
Opened 2021-09-21 13:14 UTC by dtvalk-ov

# Description

Introduce pages as a new publication type and introduce the newly developed “pages” endpoint to be monitored.

## Why
[Jira Ticket](https://financialtimes.atlassian.net/browse/UPPSF-2694)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-09-27 15:42 UTC, atanasdinov requested changes
The page notifications URL must also be removed from the other app configs, templates and docs.

Other than that the changes look good. The easiest way to test would be to use the `US` environment to publish pages and follow PAM's logs and reports once we get to staging.

2021-09-27 15:42 UTC, atanasdinov commented on helm/publish-availability-monitor/app-configs/publish-availability-monitor_eks_publish_dev.yaml
> +  pages_notifications_url: "/__notifications-rw/pages/notifications"
There isn't a configured GET endpoint at this route. Page notifications are read from `GET /content/notifications` similarly to the other types.

The currently existing `notifications_url` values should be enough to fetch page notifications however this needs to be tested manually.

2021-09-28 10:52 UTC, atanasdinov approved these changes

2021-09-29 08:47 UTC, Zarrie approved these changes
LGTM 👍

2021-09-30 08:02 UTC, merged