Remove Methode related code
Financial-Times/publish-availability-monitor pull request #196
Opened 2021-11-24 17:16 UTC by MiroslavGatsanoga

# Description

## What

Remove Methode related code.

## Why

[JIRA ticket](https://financialtimes.atlassian.net/browse/UPPSF-2818).

## Scope and particulars of this PR (Please tick all that apply)

- [X] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-11-26 16:38 UTC, atanasdinov requested changes
Looks great to me! Aside from the minor comments, I also noticed that there are stale examples in the `example-config.json` and the UUID resolving is not used anymore and could be removed.

Happy to approve after that's addressed.

2021-11-26 16:38 UTC, atanasdinov commented on healthcheck.go
> -	"S3": buildAwsHealthcheckUrl,
The `buildAwsHealthcheckUrl` along with its test usages could also be removed.

2021-11-26 16:38 UTC, atanasdinov commented on checks/preCheck.go
>  func getValidationEndpointKey(publishedContent content.Content, tid string, uuid string) string {
A nitpick but this function is now equivalent to `publishedContent.GetType()` call and is used only in once place so we can remove it altogether.

2021-11-29 14:58 UTC, atanasdinov approved these changes

2021-12-02 09:27 UTC, martin-stanchev approved these changes
LGTM

2021-12-02 11:31 UTC, merged