Migrate to MSK
Financial-Times/publish-availability-monitor pull request #199
Opened 2022-09-16 07:11 UTC by elenasuteva

# Description

## What

Using the Kafka-client-go/v3 library replaced the consumer of Kafka messages;
Updated env vars;
Replace logrus with upp logger v2;
Updated go version to 18;
Fixed tests.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-3491

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-09-20 07:06 UTC, atanasdinov requested changes

2022-09-20 07:06 UTC, atanasdinov commented on config.json.template
>      "address": [
Is this now obsolete with the addition of `connectionString`?

2022-09-20 07:06 UTC, atanasdinov commented on config/config.go
> +	KafkaLagTolerance       string   `json:"lagTolerance"`
Is there a reason for not using `int` directly? We need to manually convert this later.

2022-09-20 07:06 UTC, atanasdinov commented on README.md
> +	"ConsumerGroup": "YourGroupName",
This being in PascalCase doesn't really make sense to me? Is it tested?

2022-09-20 07:06 UTC, atanasdinov commented on main.go
>  	var wg sync.WaitGroup
A wait group is not needed anymore.

2022-09-20 07:08 UTC, atanasdinov commented
Also the PR states that `logrus` is replaced but in fact it's used in many places. It's still probably not the best idea to change those usages in this PR tho.

2022-09-20 10:42 UTC, elenasuteva commented on config/config.go
> +	KafkaLagTolerance       string   `json:"lagTolerance"`
The reason is that JSON unmarshalling was failing on dev. I am going to inspect this once again and try to change it to int. I think that the reason for failing is config.json parses "" for kafkaLagTolerance if not set correctly.

2022-09-20 11:57 UTC, atanasdinov commented on config/config.go
> +	KafkaLagTolerance       string   `json:"lagTolerance"`
I suppose that issue had been caused by the value being string in the JSON itself instead of integer.

2022-09-20 14:55 UTC, elenasuteva commented on config/config.go
> +	KafkaLagTolerance       string   `json:"lagTolerance"`
I've fixed it now I think and tested it.

2022-09-21 08:47 UTC, ilian2233 commented on checks/preCheck.go
> +	log "github.com/sirupsen/logrus"
Shouldn't we replace `github.com/sirupsen/logrus` with `github.com/Financial-Times/go-logger/v2`

2022-09-21 08:47 UTC, ilian2233 commented on go.mod
> +go 1.18
**nitpick (non-blocking):** can be updated to 1.19

2022-09-21 08:47 UTC, ilian2233 commented on logformat/logFormatter.go
>  	"runtime"
**question (non-blocking):** Is that file ever used?

Maybe should be removed?

2022-09-26 13:07 UTC, martin-stanchev approved these changes

2022-09-27 06:31 UTC, martin-stanchev approved these changes

2022-09-27 07:12 UTC, dtvalk-ov approved these changes

2022-09-28 09:02 UTC, atanasdinov approved these changes

2022-09-28 09:02 UTC, merged