Properly enable the content checks for our ContentRelation type.
Financial-Times/publish-availability-monitor pull request #208
Opened 2024-06-19 13:46 UTC by todor-videv1

# Description

## What

This PR intends to enable proper validation and monitoring of our ContentRelation type.
Basically, it comprises the necessary work to have a new configuration for publication monitoring by the PAM.

## Why

There were several errors flagged by the OpsCops rota where the PAM was trying to find a published/republished ContentRelation looking at the wrong place. This wrong place was the /content endpoint. Since we do not write ContentRelation in the standard collection in the Document Store, this would never work.

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [x] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)
___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2024-06-19 13:57 UTC, ManoelMilchev approved these changes
LGTM! Just one small change!

2024-06-19 13:57 UTC, ManoelMilchev commented on config.json.template
> +        "application/vnd.ft-upp-content-relation+json"
`suggestion`: This is great, just remove the content type from the content configuration.

2024-06-19 13:57 UTC, ManoelMilchev requested changes
LGTM! Just one small change

2024-06-19 14:34 UTC, tsvetko24 commented on config.json.template
> +        "application/vnd.ft-upp-content-relation+json"
Row 29 must disappear, right?

2024-06-19 14:35 UTC, ManoelMilchev commented on config.json.template
> +        "application/vnd.ft-upp-content-relation+json"
yup

2024-06-19 14:46 UTC, tsvetko24 submitted a review, later dismissed

2024-06-20 05:23 UTC, antoanFT submitted a review, later dismissed

2024-06-21 10:22 UTC, ManoelMilchev approved these changes

2024-06-21 10:56 UTC, tsvetko24 approved these changes

2024-06-26 13:16 UTC, merged